-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION IF EXISTS pg_net;

DROP EXTENSION IF EXISTS pg_graphql;

-- CREATE ROLE supabase_privileged_role;

-- GRANT supabase_privileged_role TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE TABLE public.artworks (
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL,
  title         text,
  description   text,
  price         numeric                  DEFAULT '0'::numeric,
  image_path    text,
  publish_on    timestamp with time zone,
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  sold          boolean                  DEFAULT false NOT NULL,
  dimensions    text,
  collection_id uuid                     DEFAULT gen_random_uuid() NOT NULL,
  cover_image   boolean                  DEFAULT false NOT NULL,
  artwork_note  text                     DEFAULT ''::text
);

ALTER TABLE public.artworks
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.artworks
  ADD CONSTRAINT artworks_pkey PRIMARY KEY (id);

GRANT ALL ON public.artworks TO anon;

GRANT ALL ON public.artworks TO authenticated;

GRANT ALL ON public.artworks TO service_role;

CREATE POLICY "Allow public to access artworks" ON public.artworks
  FOR SELECT
  USING (true);

CREATE POLICY "Only admin can insert artworks" ON public.artworks
  FOR INSERT
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only logged in user can delete artworks" ON public.artworks
  FOR DELETE
  USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only logged in user can update artworks" ON public.artworks
  FOR UPDATE
  USING ((auth.role() = 'authenticated'::text))
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE TABLE public.collections (
  id              uuid                     DEFAULT gen_random_uuid() NOT NULL,
  collection_name text                     NOT NULL,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  "desc"          text
);

ALTER TABLE public.collections
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.collections
  ADD CONSTRAINT collections_pkey PRIMARY KEY (id);

ALTER TABLE public.artworks
  ADD CONSTRAINT artworks_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id);

GRANT ALL ON public.collections TO anon;

GRANT ALL ON public.collections TO authenticated;

GRANT ALL ON public.collections TO service_role;

CREATE POLICY "Only authenticated users can delete" ON public.collections
  FOR DELETE
  USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only authenticated users can insert" ON public.collections
  FOR INSERT
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only authenticated users can update" ON public.collections
  FOR UPDATE
  USING ((auth.role() = 'authenticated'::text))
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Public can view collections" ON public.collections
  FOR SELECT
  USING (true);

CREATE TABLE public.cover_images (
  id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  image_path text                     NOT NULL
);

ALTER TABLE public.cover_images
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cover_images
  ADD CONSTRAINT cover_images_pkey PRIMARY KEY (id);

GRANT ALL ON public.cover_images TO anon;

GRANT ALL ON public.cover_images TO authenticated;

GRANT ALL ON public.cover_images TO service_role;

CREATE POLICY "Any one can select cover image" ON public.cover_images
  FOR SELECT
  USING (true);

CREATE POLICY "Only auth users can delete" ON public.cover_images
  FOR DELETE
  USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only auth users can insert" ON public.cover_images
  FOR INSERT
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only auth users can update" ON public.cover_images
  FOR UPDATE
  USING ((auth.role() = 'authenticated'::text))
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE TABLE public.gallery_images (
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  artwork_id uuid                     DEFAULT gen_random_uuid() NOT NULL,
  image_path text,
  id         uuid                     DEFAULT gen_random_uuid() NOT NULL,
  "order"    smallint                 NOT NULL
);

ALTER TABLE public.gallery_images
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gallery_images
  ADD CONSTRAINT gallery_images_artwork_id_fkey FOREIGN KEY (artwork_id) REFERENCES public.artworks(id);

ALTER TABLE public.gallery_images
  ADD CONSTRAINT gallery_images_pkey PRIMARY KEY (id);

GRANT ALL ON public.gallery_images TO anon;

GRANT ALL ON public.gallery_images TO authenticated;

GRANT ALL ON public.gallery_images TO service_role;

CREATE POLICY "Anyone can view gallery images" ON public.gallery_images
  FOR SELECT
  USING (true);

CREATE POLICY "Only authenticated users can delete gallery images" ON public.gallery_images
  FOR DELETE
  USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only authenticated users can insert gallery images" ON public.gallery_images
  FOR INSERT
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only authenticated users can update gallery images" ON public.gallery_images
  FOR UPDATE
  USING ((auth.role() = 'authenticated'::text))
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE TABLE public.orders (
  created_at                 timestamp with time zone DEFAULT now() NOT NULL,
  amount                     numeric,
  artwork_id                 uuid,
  buyer_email                text                     NOT NULL,
  status                     text                     DEFAULT 'PAID'::text NOT NULL,
  stripe_payment_intent_id   text,
  updated_at                 timestamp with time zone DEFAULT now(),
  country                    text,
  state                      text,
  postal_code                text,
  address_line_1             text                     NOT NULL,
  address_line_2             text,
  city                       text,
  id                         uuid                     DEFAULT gen_random_uuid() NOT NULL,
  stripe_checkout_session_id text,
  buyer_name                 text                     NOT NULL,
  shipping_cost              numeric                  NOT NULL
);

ALTER TABLE public.orders
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

GRANT ALL ON public.orders TO anon;

GRANT ALL ON public.orders TO authenticated;

GRANT ALL ON public.orders TO service_role;

CREATE POLICY "Only auth users can  access orders" ON public.orders
  FOR SELECT
  USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only auth users can delete orders" ON public.orders
  FOR DELETE
  USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Only auth users can update orders" ON public.orders
  FOR UPDATE
  USING ((auth.role() = 'authenticated'::text))
  WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE TABLE public.webhook_event (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  event_id      text                     NOT NULL,
  status_type   text                     DEFAULT '''PENDING'''::text NOT NULL,
  error_message text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL,
  processed_at  timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.webhook_event
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.webhook_event
  ADD CONSTRAINT webhook_event_pkey PRIMARY KEY (id);

GRANT ALL ON public.webhook_event TO anon;

GRANT ALL ON public.webhook_event TO authenticated;

GRANT ALL ON public.webhook_event TO service_role;
